server:
  shutdown: immediate

api.base.url:
  hmpps-auth: http://localhost:8090/auth
  alerts-api: http://localhost:8093

opensearch:
  uris: http://os01.eu-west-2.opensearch.localhost.localstack.cloud:4566

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
