---
generic-service:
  nameOverride: hmpps-prisoner-search-indexer

  serviceAccountName: hmpps-prisoner-search-indexer

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-prisoner-search-indexer
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-prisoner-search-indexer-cert
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  namespace_secrets:
    hmpps-prisoner-search-indexer:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      RESTRICTED_PATIENTS_CLIENT_ID: "RESTRICTED_PATIENTS_CLIENT_ID"
      RESTRICTED_PATIENTS_CLIENT_SECRET: "RESTRICTED_PATIENTS_CLIENT_SECRET"
      PRISON_API_CLIENT_ID: "PRISON_API_CLIENT_ID"
      PRISON_API_CLIENT_SECRET: "PRISON_API_CLIENT_SECRET"
      INCENTIVES_CLIENT_ID: "INCENTIVES_CLIENT_ID"
      INCENTIVES_CLIENT_SECRET: "INCENTIVES_CLIENT_SECRET"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    prisoner-search-indexer-dlq:
      HMPPS_SQS_QUEUES_INDEX_DLQ_NAME: "sqs_queue_name"
    prisoner-search-indexer-queue:
      HMPPS_SQS_QUEUES_INDEX_QUEUE_NAME: "sqs_queue_name"

    opensearch:
      OPENSEARCH_URIS: "url"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-search-indexer
  alertSeverity: syscon

